### ISSUE TITLE
Add random responses

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/slack-bot#16]
After test bot with other organizers i think we can add more answers for these questions:

- [ ] I am not joking: _NotJoke_
- [ ] Who are you: _WhoAreYou_
- [ ] Who is your father: _Father_
- [ ] Be clever: _BeClever_
- [ ] You are clever: _IsClever_
- [ ] How old are you ?: _Age_
- [ ] You are funny: _IsFunny_
- [ ] Answer my question: _AnswerGood_
- [ ] Are you single?: _Single_

**Comment by elena20ruiz** [comment]
What do you think @AlbertSuarez  ?

**Comment by elena20ruiz** [comment]
And @oriolclosa  I think that it will funny for you give more ideas jajajaj

**Comment by AlbertSuarez** [comment]
@elena20ruiz All responses added into json file. Just need to add to LUIS.

**Comment by elena20ruiz** [comment]
Done @albertsuarez
