### ISSUE TITLE
Add color to T-Shirt response

### ISSUE THREAD

**Issue by felixarpa** [elena20ruiz/slack-bot#17]
In Slack, when you type #XXXXXX it shows the color (HEX) in a square.

In responses like: _Are you okay? If you are in trouble, please ping directly @felix and @marina and find an organizer. There are 25 around the venue. All of us are wearing Navy Blue T-shirts._ It could show the color next to _Navy Blue_

**Comment by AlbertSuarez** [comment]
Issue solved in PR #20
