### ISSUE TITLE
Implement BIENE outside LUIS

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/slack-bot#2]
Implement the BIENE response outside luis, when independent of intent send BIENE message if contain the  word correctly.

**Comment by elena20ruiz** [comment]
Deleted **Smalltalk.Biene** intent.
Now, for each input on code analyze if contains the word BIENE

**Comment by elena20ruiz** [comment]
Sorry, I will maintain the intent Smalltalk.Biene in case that only contains the word Biene. In other case LUIS can't detect any intent an answer _don't understand_

**Comment by elena20ruiz** [comment]
https://github.com/elena20ruiz/slack-bot/tree/biene-response

**Comment by AlbertSuarez** [comment]
Done in PR #7
