### ISSUE TITLE
Create new intent

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/slack-bot#23]
Remove meals intent from Logistics and make it independent.

Intent meals: 

- [x] Schedule: _Meals.Schedule_
- [x] Which meals are going to be? _Meals.Which_
- [x] There are special meals (vegetarian/vegan/intolerant/no pork) ? _Meals.Special_
- [x] There are coffee? _Meals.Coffee_
- [x] There are snacks ? _Meals.Snacks_
- [x] Where is the food? _Meals.Where_
- [x] What can you say about meals? _Meals.Help_

**Comment by elena20ruiz** [comment]
Done, put responses on the code. Migrate some responses from Logistics. Meals to corresponding intent.

**Comment by AlbertSuarez** [comment]
I've just seen LUIS Intents and there's no _Meals.List_ but there is _Meals.Which_. Can you help me with that?

**Comment by AlbertSuarez** [comment]
Done :heavy_check_mark:
