### ISSUE TITLE
Add new necessary intents / add utterances

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/slack-bot#24]
New intents from existing groups: 

- [x] From HackUPC intent: HackUPC Schedule -> _HackUPC.Schedule_
- [x] From HackUPC intent: What's next? -> _HackUPC.Next_

New utterances from existing intents:

- [ ] From Logistics.Where:  _Where can I bring my bag?_

**Comment by AlbertSuarez** [comment]
Would be really cool to add _What's next?_ question.

**Comment by AlbertSuarez** [comment]
Intents and code added for the first second tasks. The last one doesn't depend of this repository, it's an internal thing from LUIS which @elena20ruiz is gonna fix.
