### ISSUE TITLE
Spanish/Catalan questions

### ISSUE THREAD

**Issue by elena20ruiz** [elena20ruiz/slack-bot#4]
Decide what to do with catalan and spanish question. Include them on each LUIS intent, or ask to hacker to speak in English?

**Comment by AlbertSuarez** [comment]
I would ask to hacker to speak in English. At the end HackUPC is an english event, so doesn't make sense to spent hours implementing a bot which can understand more languages than English, IMO.

**Comment by elena20ruiz** [comment]
We can add a LUIS new intent with phrases in others languages and tell the user that bot only can understand English

**Comment by AlbertSuarez** [comment]
That would be really great!

**Comment by elena20ruiz** [comment]
I did **Smalltalk.DifLanguage** intent to put some questions in other Languages, now I will put bot responses for this intent.

**Comment by elena20ruiz** [comment]
Branch assigned: https://github.com/elena20ruiz/slack-bot/tree/issue-language

**Comment by AlbertSuarez** [comment]
Great. Please create a PR whenever it's ready and I'll review it

**Comment by elena20ruiz** [comment]
@AlbertSuarez  if you want you can add more Biene bot responses for this intent on: 
https://github.com/elena20ruiz/slack-bot/blob/issue-language/hackupc/bienebot/responses/smalltalk/smalltalk_data.json

**DifLanguage** element
